require("core.plugin_config.lualine")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.lsp")
require("core.plugin_config.dracula")
require("core.plugin_config.git-config")
require("core.plugin_config.harpoon")
require("core.plugin_config.neo-tree")
--require("core.plugin_config.window-picker")
require("core.plugin_config.nerdcommenter")
require("core.plugin_config.catppuccin")
require("core.plugin_config.aerial")
require("core.plugin_config.diagflow")
require("core.plugin_config.trouble")
require("core.plugin_config.tokyo")
require("core.plugin_config.barbecue")
require("core.plugin_config.mini")
require("core.plugin_config.indent")
require("core.plugin_config.spectre")
require("core.plugin_config.navbuddy")
require("core.plugin_config.icon-picker")

vim.cmd [[colorscheme tokyonight]]
