require("core.plugin_config.lualine")
require("core.plugin_config.telescope")
require("core.plugin_config.treesitter")
require("core.plugin_config.lsp")
require("core.plugin_config.dracula")
require("core.plugin_config.git-config")
require("core.plugin_config.harpoon")
require("core.plugin_config.neo-tree")
